Fix the scripts to plot weights
iotaledger/multiverse-simulation pull request #48
Opened 2021-09-23 13:11 UTC by bingyanglin

2021-09-23 13:56 UTC, piotrm50 commented
`35f338da` this commit deleted a lot of changes that we did with Daria on friday. e.g. we refactored the condition to shutdown the script. Could you take a look at it?

2021-09-23 14:02 UTC, piotrm50 requested changes
One commit with a lot of changes was overwritten. Need to discuss this.

2021-09-23 14:51 UTC, bingyanglin commented
> `35f338da` this commit deleted a lot of changes that we did with Daria on friday. e.g. we refactored the condition to shutdown the script. Could you take a look at it?

Thanks for pointing this out. I reverted the commit.

2021-09-24 07:08 UTC, daria305 approved these changes

2021-09-24 09:03 UTC, merged